# Generated by Django 6.0.2 on 2026-02-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('issue_date', models.DateField()),
                ('text', models.TextField(max_length=100)),
                ('register_type', models.TextField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound')], default='IN', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('associated_company', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('cpf_cnpj', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
