# Generated by Django 6.0.2 on 2026-02-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='credit_account',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='debit_account',
            field=models.CharField(default='', max_length=100),
        ),
    ]
