# Generated by Django 6.0.2 on 2026-02-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0002_register_credit_account_register_debit_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('register_date', models.DateField()),
                ('cpf_cnpj', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='register',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='register',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_type',
            field=models.TextField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='associated_company',
            field=models.IntegerField(),
        ),
    ]
